-- MySQL Script generated by MySQL Workbench
-- Wed Jun 26 16:43:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SafeTrade
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SafeTrade` ;

-- -----------------------------------------------------
-- Schema SafeTrade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SafeTrade` DEFAULT CHARACTER SET utf8 ;
USE `SafeTrade` ;

-- -----------------------------------------------------
-- Table `SafeTrade`.`Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeTrade`.`Usuário` ;

CREATE TABLE IF NOT EXISTS `SafeTrade`.`Usuário` (
  `Id_Usuario` INT NOT NULL,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `foto` BLOB NULL,
  PRIMARY KEY (`Id_Usuario`),
  UNIQUE INDEX `Id_Usuario_UNIQUE` (`Id_Usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeTrade`.`Postagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeTrade`.`Postagem` ;

CREATE TABLE IF NOT EXISTS `SafeTrade`.`Postagem` (
  `idPostagem` INT NOT NULL AUTO_INCREMENT,
  `Usuario_Postagem_Id` INT NOT NULL,
  `título` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(250) NOT NULL,
  `foto` BLOB(400) NULL,
  `dataPostagem` DATE NOT NULL,
  `horaPostagem` TIME NOT NULL,
  PRIMARY KEY (`idPostagem`, `Usuario_Postagem_Id`),
  INDEX `fk_Postagem_Usuário1_idx` (`Usuario_Postagem_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Postagem_Usuário1`
    FOREIGN KEY (`Usuario_Postagem_Id`)
    REFERENCES `SafeTrade`.`Usuário` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeTrade`.`Oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeTrade`.`Oferta` ;

CREATE TABLE IF NOT EXISTS `SafeTrade`.`Oferta` (
  `idOferta` INT NOT NULL AUTO_INCREMENT,
  `Usuario_Interessado_Id` INT NOT NULL,
  `idPostagem` INT NOT NULL,
  `horaOferta` TIME NULL,
  `dataOferta` TIME NULL,
  PRIMARY KEY (`idOferta`, `Usuario_Interessado_Id`),
  INDEX `id_Postagem_idx` (`idPostagem` ASC) VISIBLE,
  INDEX `UsuarioInteressado_idx` (`Usuario_Interessado_Id` ASC) VISIBLE,
  CONSTRAINT `id_Postagem`
    FOREIGN KEY (`idPostagem`)
    REFERENCES `SafeTrade`.`Postagem` (`idPostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UsuarioInteressado`
    FOREIGN KEY (`Usuario_Interessado_Id`)
    REFERENCES `SafeTrade`.`Usuário` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeTrade`.`Troca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeTrade`.`Troca` ;

CREATE TABLE IF NOT EXISTS `SafeTrade`.`Troca` (
  `idTroca` INT NOT NULL AUTO_INCREMENT,
  `Usuario_Postagem_Id` INT NOT NULL,
  `dataTrocaDeStatus` TIME NOT NULL,
  `statusTroca` TINYINT NOT NULL,
  `avaliacaoUsuario` INT NOT NULL,
  `avaliacaoTroca` INT NOT NULL,
  `UsuarioPostagem` VARCHAR(45) NOT NULL,
  `Oferta_idOferta` INT NOT NULL,
  `Oferta_Usuario_Interessado_Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTroca`),
  INDEX `fk_Troca_Oferta1_idx` (`Oferta_idOferta` ASC, `Oferta_Usuario_Interessado_Nome` ASC) VISIBLE,
  INDEX `Usuario_Postagem_Id_idx` (`Usuario_Postagem_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Troca_Oferta1`
    FOREIGN KEY (`Oferta_idOferta` , `Oferta_Usuario_Interessado_Nome`)
    REFERENCES `SafeTrade`.`Oferta` (`idOferta` , `Usuario_Interessado_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuario_Postagem_Id`
    FOREIGN KEY (`Usuario_Postagem_Id`)
    REFERENCES `SafeTrade`.`Postagem` (`Usuario_Postagem_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeTrade`.`Parceiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeTrade`.`Parceiro` ;

CREATE TABLE IF NOT EXISTS `SafeTrade`.`Parceiro` (
  `nome_Empresa` VARCHAR(45) NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `cnpj` INT(14) NULL,
  `detalhamento_Proposta` VARCHAR(500) NOT NULL,
  `proposta_Parceria` VARCHAR(250) NOT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  PRIMARY KEY (`nome_Empresa`),
  INDEX `Id_Usuario_idx` (`Id_Usuario` ASC) VISIBLE,
  CONSTRAINT `Id_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `SafeTrade`.`Usuário` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeTrade`.`Avaliação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SafeTrade`.`Avaliação` ;

CREATE TABLE IF NOT EXISTS `SafeTrade`.`Avaliação` (
  `Id_Usuario` VARCHAR(45) NOT NULL,
  `IdTroca` INT NOT NULL,
  `Ava_Otima` BLOB NOT NULL,
  `Ava_Regular` BLOB NOT NULL,
  `Ava_Ruim` BLOB NOT NULL,
  PRIMARY KEY (`Id_Usuario`),
  INDEX `idTroca_idx` (`IdTroca` ASC) VISIBLE,
  CONSTRAINT `id_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `SafeTrade`.`Usuário` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTroca`
    FOREIGN KEY (`IdTroca`)
    REFERENCES `SafeTrade`.`Troca` (`idTroca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
